### PR TITLE
fixed shape in load_image()/dump_image() (resolves #22)

### LINKED ISSUE #22: Incorrect shape and strides after load_image()
ximage-io claims to use the shape convention `WIDTH x HEIGHT x CHANNELS` (see http://xtensor-io.readthedocs.io/en/latest/api_reference.html#images) along with the usual c-order strides (increasing from back to front). However, this is **wrong**. 

All file formats store images such that the WIDTH axis has smaller stride than the HEIGHT axis, and *xtensor-io reads the memory unchanged*. This means that the shape must be `HEIGHT x WIDTH x CHANNELS` with corresponding strides. All other libraries that follow the c-order convention use this shape, see for example scikit-image. You can easily verify the error with a simple program:
```c++
        auto in  = xt::load_image("color_image.tif");
        for(int y=0; y<in.shape()[1]; ++y)
        {
            in(100, y, 1) = 255;
        }
        xt::dump_image("result.tif", in);
```
This should draw a vertical line, but actually draws a horizontal one.

### PR DESCRIPTION
**Pull request by ukoethe**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Thanks, this looks good to me.

**Comment by ukoethe** [comment]
Thanks. Please update the documentation to avoid people getting really confused.

**Comment by wolfv** [comment]
ah, this really makes sense now. 
I tested 2 different images, but the first one was quadratic so it looked kinda correct :)

**Comment by ukoethe** [comment]
> I tested 2 different images, but the first one was quadratic so it looked kinda correct

I made it a rule to never use quadratic images in any test (unless semantically required). Otherwise, it's too easy for errors like this to slip through.

**Comment by wolfv** [comment]
good idea! we shall keep it in mind :)

**Pull request merged**
