### PR TITLE
WIP xhdf5 support

### PR DESCRIPTION
**Pull request by wolfv**
This adds initial support for the HDF5 file format. However, a lot of details API wise have to be ironed out... community support wanted!

### CODE REVIEW

**Comment by wolfv** [comment]
Maybe it would be better to just add some way of automatic casting as a free function? That way people would "stay" in the HighFive API and we would take care only of the conversion from `HighFive::DataSet` <-> `xtensor/xarray` and don't need to think about groups etc. pp.

**Comment by tdegeus** [comment]
Staying the HighFive API would make a lot of sense!  As a user I can say that I also frequently use `std::string` and extendible datasets. It would be annoying to switch between APIs to use such features. Moreover because I think that one file cannot be opened more than once.

**Comment by tdegeus** [comment]
@wolfv 

OK, I will make a new PR (not today though). What do you think of the proposed syntax?

**Comment by wolfv** [comment]
Closing in favor of #41

**Pull request closed without merging**
