### PR TITLE
Allow image IO for value_types other than uint8_t

### PR DESCRIPTION
**Pull request by ukoethe**
This PR relies on https://github.com/QuantStack/xtensor/pull/698 (therefore, Travis tests fail right now).

Support for floating-point I/O is crucial for testing image processing algorithms.

### CODE REVIEW

**Comment by wolfv** [comment]
Hey Ullrich,

thanks for helping us out with this, it's really much appreciated!

Wolf

**Comment by ukoethe** [comment]
Travis fails because it installs xtensor 0.15.5, which doesn't contain `minmax()`.

**Comment by SylvainCorlay** [comment]
Yeah, next xsimd and xtensor 0.15.6 should come up soon. Especially because of the performance improvements.

**Comment by JohanMabille** [comment]
@ukoethe I think you can now bump the version of xtensor in .travis.yml since xtensor 0.15.6 is out.

**Comment by ukoethe** [comment]
> you can now bump the version of xtensor

Yes, tests succeed now. I think the PR is good for merge.

**Comment by wolfv** [comment]
Thanks for the contribution!

**Pull request merged**
