### PR TITLE
Update xtensor

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
OK, this builds correctly but the equality test for compressed files appears to be failing.

**Comment by wolfv** [comment]
the problem might be that we're in another year and the timestamp doesn't match up ...?

**Comment by wolfv** [comment]
nope, doesn't make sense I merged a PR yesterday that didn't fail like this...

**Comment by wolfv** [comment]
I think we might have changed something in linspace!

**Comment by JohanMabille** [comment]
Superseded by #55

**Pull request closed without merging**
